---
- name: Setup PostgreSql container
  hosts: databases
  become: true

  tasks:
    - name: Create docker volume if it is not found
      community.docker.docker_volume:
        name: postgres_data
        state: present

    - name: Create Postgres Container
      no_log: false
      community.docker.docker_container:
        name: postgres
        image: postgres:17.0-alpine3.19
        state: started
        recreate: true
        restart: true
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"

    - name: Ensure pip is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true

- name: PIP install psycopg2-binary
  hosts: lxc, vm
  become: true
  tasks:
    - name: Install psycopg2-binary
      ansible.builtin.pip:
        name: psycopg2-binary
        state: present

- name: APT install psycopg2-binary
  hosts: pi
  become: true

  tasks:
    - name: Install python3-psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

- name: Install PostgreSQL Client
  hosts: databases
  become: true

  tasks:
    - name: Install PostgreSQL Client
      ansible.builtin.apt:
        name: postgresql-client
        state: present
        force_apt_get: true
        install_recommends: false
        update_cache: true
