---
- name: Setup PostgreSql container
  hosts: postgres
  become: true

  tasks:
    - name: Create docker volume if it is not found
      community.docker.docker_volume:
        name: posgres_data
        state: present

    - name: Create Postgres Container
      # enable no_log to prevent POSTGRES_PASSWORD from being exposed when the -v option is used
      no_log: true
      community.docker.docker_container:
        name: postgres
        image: postgres:17.0-alpine3.19
        state: started
        recreate: true
        restart: true
        ports:
          - "5432:5432"
        volumes:
          - posgres_data:/var/lib/postgresql/data
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"

    - name: Create Scratch DB
      community.postgresql.postgresql_db: 
        name: acme
        comment: My test DB
     

